parameters: {}
environment: {}
packages:
  - name: sample
    environment: {}
    parameters: {}
    functions:
      - name: random
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}